// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsoGp303gi3aFHxctNSYfxloLMtCcaqAU',
    appId: '1:493286135952:web:53105e2b4daceb9052e015',
    messagingSenderId: '493286135952',
    projectId: 'instagram-clone-64e9b',
    authDomain: 'instagram-clone-64e9b.firebaseapp.com',
    storageBucket: 'instagram-clone-64e9b.appspot.com',
    measurementId: 'G-G9TGYLGLT8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlK9D6kmL_ITNJZmdmj-3_Lc0Lr1bg_54',
    appId: '1:493286135952:android:3cdd2066c83efdc152e015',
    messagingSenderId: '493286135952',
    projectId: 'instagram-clone-64e9b',
    storageBucket: 'instagram-clone-64e9b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0tK5MyKZcWGyCHXgs02JYYFNEJ_9gILc',
    appId: '1:493286135952:ios:21b43839b0e4ee6b52e015',
    messagingSenderId: '493286135952',
    projectId: 'instagram-clone-64e9b',
    storageBucket: 'instagram-clone-64e9b.appspot.com',
    iosClientId:
        '493286135952-jn98qpc571qev3fa82kd1jdbf86hih3s.apps.googleusercontent.com',
    iosBundleId: 'com.example.instragramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0tK5MyKZcWGyCHXgs02JYYFNEJ_9gILc',
    appId: '1:493286135952:ios:21b43839b0e4ee6b52e015',
    messagingSenderId: '493286135952',
    projectId: 'instagram-clone-64e9b',
    storageBucket: 'instagram-clone-64e9b.appspot.com',
    iosClientId:
        '493286135952-jn98qpc571qev3fa82kd1jdbf86hih3s.apps.googleusercontent.com',
    iosBundleId: 'com.example.instragramClone',
  );
}
